  <footer id="footer">
    <div class="container">
      <div class="social text-center">
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-dribbble"></i></a>
        <a href="#"><i class="fa fa-flickr"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
      </div>

      <div class="clear"></div>
      <!--CLEAR FLOATS-->
    </div>
    <div class="footer2">
      <div class="container">
        <div class="row">

          <div class="col-md-6 panel">
            <div class="panel-body">
              <p class="simplenav">
                <a href="index.html">Inicio</a> | 
                <a href="about.html">Acerca De</a> |
                <a href="courses.html">Cursos</a> |
                <a href="fees.html">Matricula</a> |
                <a href="portfolio.html">Portfolio</a> |
                <a href="contact.html">Contactos</a>
              </p>
            </div>
          </div>

          <div class="col-md-6 panel">
            <div class="panel-body">
              <p class="text-right">
                Copyright &copy; <?php echo Date('Y') ?>. Template by <a href="http://jaig.net.ve/" rel="develop">Jaig.net.ve</a>
              </p>
            </div>
          </div>

        </div>
        <!-- /row of panels -->
      </div>
    </div>
  </footer>

  <!-- JavaScript libs are placed at the end of the document so the pages load faster -->
 