	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse">
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
				<a class="navbar-brand" href="<?php echo PUBLIC_PATH ?>">
					<?php echo Html::img('logo_poder3000.png',"No Image","width='100' height='75'") ?>

					<br><br>
					<!-- <img src="assets/images/logo.png" alt="Techro HTML5 template"></a> -->
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right mainNav">
					<li class="active"><a href="<?php echo PUBLIC_PATH ?>">Inicio</a></li>
					<li><a href="about.html">Acerca De</a></li>
					<li><a href="courses.html">Cursos</a></li>
					<li><a href="fees.html">Matricula</a></li>
					<li><a href="portfolio.html">Portfolio</a></li>
					<!-- <li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Paginas (por definir) <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="sidebar-right.html">Right Sidebar</a></li>
							<li><a href="#">Dummy Link1</a></li>
							<li><a href="#">Dummy Link2</a></li>
							<li><a href="#">Dummy Link3</a></li>
						</ul>
					</li> -->
					<li><a href="contact.html">Contactenos</a></li>

				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</div>
	<!-- /.navbar -->