<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="eLearning is a modern and fully responsive Template by WebThemez.">

  <title>eLearning -  Educational  </title>
  <link rel="favicon" href="<?php echo PUBLIC_PATH ?>assets/images/favicon.png">
  <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>assets/css/bootstrap.min.css">
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>assets/css/font-awesome.min.css">
  <!-- Custom styles for our template -->
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>assets/css/bootstrap-theme.css" media="screen">
  <link rel="stylesheet" type="text/css" href="<?php echo PUBLIC_PATH ?>assets/css/da-slider.css" />
  <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>assets/css/style.css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="assets/js/html5shiv.js"></script>
  <script src="assets/js/respond.min.js"></script>
  <![endif]-->

  <!--<?php //Tag::css('kumbia') ?>-->
  <?= Html::includeCss() ?>
 <script src="<?php echo PUBLIC_PATH ?>assets/js/modernizr-latest.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="<?php echo PUBLIC_PATH ?>assets/js/jquery.cslider.js"></script>
  <script src="<?php echo PUBLIC_PATH ?>assets/js/custom.js"></script>
</head>
<body>
  <?php View::partial('navbar') ?>
  <?php View::content() ?>
  <?php View::partial('footer') ?>
</body>
</html>
